### ISSUE TITLE
mhd_linear stride annotation silently disappears from the eigenfunction figure after an IMAS round trip

### ISSUE THREAD

**Issue by HongSik-Yun-Fusion** [VEST-Tokamak/vaft#560]
## What happens

`_mhd_linear_radial_stride` (`vaft/plot/backend/recipes.py:6012-6020`) recovers the mapper's radial stride by regexing the raw XML:

```python
parameters = _get(ods, "mhd_linear.code.parameters", "") or ""
strides = {int(value) for value in re.findall(r'radial_stride="(\d+)"', str(parameters))}
```

That works on an ODS loaded from the FileDB JSON product, where the field is still a string. It does not work on an ODS loaded through IMAS/HSDS, because OMAS converts the field into a `CodeParameters` dict on that path — `vaft/imas/omas_imas.py:1025` decorates `load_omas_imas` with `@codeparams_xml_load`, which calls `ods.codeparams2dict()` (`omas/omas_core.py:2786-2792`). `vaft/database/ods.py:346,390` and `vaft/database/_local.py:283` all go through that loader.

Reproduced against omas 0.94.2:

```python
ods["mhd_linear.code.parameters"] = '<parameters><solver name="dcon"><eigenfunction_grid radial_stride="3"/></solver></parameters>'
re.findall(r'radial_stride="(\d+)"', str(ods["mhd_linear.code.parameters"]))   # ['3']
ods.codeparams2dict()
type(ods["mhd_linear.code.parameters"]).__name__                               # 'CodeParameters'
repr(...)   # {'solver': {'@name': 'dcon', 'eigenfunction_grid': {'@radial_stride': 3}}}
re.findall(r'radial_stride="(\d+)"', str(...))                                 # []
```

## Why it matters

The stride is not decoration. What reaches the IDS is a radially strided view of `solutions.bin` (`vaft/machine_mapping/mhd_linear.py:187-195`, `MAX_RADIAL_POINTS = 256`), and the annotation is what stops a reader mistaking the drawn resolution for DCON's own. The consumer is `recipes.py:6079-6081`, which appends "every Nth radial sample" to the eigenfunction figure's title.

The failure is silent and one-directional: `strides` comes back empty, `len(strides) == 1` is false, the function returns `None`, and the note is simply omitted. A figure rendered from an HSDS-loaded ODS therefore looks like a full-resolution eigenfunction. No warning, no error.

The existing test (`test/test_mhd_linear_validation_plots.py:211-215`) builds its ODS in memory, so the field is still a string and the regex passes — the covered path is the one that works.

## Suggested fix

Read the value shape-agnostically rather than by regex: handle both the XML string and the `CodeParameters`/dict form (the attribute surfaces as `@radial_stride` and is already an `int`). A regression test should assert the annotation survives `codeparams2dict()`, since that is the transformation that breaks it.

Introduced in #504.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by HongSik-Yun-Fusion** [comment]
Correcting the scope I claimed above. The mechanism is right; the blast radius is not.

Whether OMAS decodes `code.parameters` depends on the document, and VAFT usually produces the shape that does *not* decode:

| document | `codeparams2dict()` | the stride regex |
| --- | --- | --- |
| one `<solver>` fragment | decodes to `CodeParameters` | **fails** — returns `[]` |
| two or more `<solver>` fragments | raises `AttributeError("'list' object has no attribute 'keys'")` internally, prints `Issue with mhd_linear.code.parameters: ...`, and leaves the string untouched | works |

`_append_code_parameters` emits one `<solver>` per (module, n_tor) mapping call, so any shot mapped with several modules or modes lands in the second row and keeps working. Only a single-fragment document — one module, one mode — loses the annotation.

So the string-only reader was working **by accident** on the common case, which is why the existing test never caught it: `test/test_mhd_linear_validation_plots.py` builds its ODS in memory, and even after `codeparams2dict()` a multi-fragment document stays a string.

That makes this narrower than I first wrote, but not less worth fixing — depending on an upstream decode *failing* to keep a reader working is not a property to rely on.

There is also a second observation worth separating out: OMAS cannot decode repeated `<solver>` elements at all. `code.parameters` therefore does not reliably round-trip through IMAS for VAFT's multi-fragment documents — it survives only because the decode gives up. That is upstream behaviour and out of scope here, but it bears directly on #561's payload design, so noting it there too.

Fixed in #570, with the regression test parametrized over both shapes.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by HongSik-Yun-Fusion** [comment]
## Triage 2026-09-06 — still open, verified against `develop` @ `86c7a24`

**Sequence.** Wave 0 — independent, no dependencies. Introduced in #504 (merged 2026-09-04).

**Coverage today.** The existing test (`test_mhd_linear_validation_plots.py:211`) builds its ODS in memory, so it covers only the path that works.

**Remaining scope.** Verified unchanged on `develop`: `_mhd_linear_radial_stride` has moved to `recipes.py:6735` but the regex is identical. Same exposure applies to `ods_from_toplevels` (`vaft/imas/omas_imas.py:956`), also `@codeparams_xml_load`-decorated and used by the plotting adapters. The regression test must cross `codeparams2dict()` — that is the transformation that breaks it.

**Comment by HongSik-Yun-Fusion** [comment]
Fixed on `develop` by `9577c26` ("Read the eigenfunction stride whatever shape code.parameters
arrives in"), which landed after my triage comment above was written — that comment was accurate at
`86c7a24` and is now superseded.

**Current code path** (`vaft/plot/backend/recipes.py:6940`) branches on the shape instead of
assuming a string:

```python
parameters = _get(ods, "mhd_linear.code.parameters", "") or ""
if isinstance(parameters, str):
    values: list[Any] = re.findall(r'radial_stride="(\d+)"', parameters)
else:
    values = _code_parameter_values(parameters, "radial_stride")
strides = {int(value) for value in values}
return strides.pop() if len(strides) == 1 else None
```

with a new helper `_code_parameter_values` (`:6924`) that walks the decoded tree, handling the
leading `@` that OMAS puts on attribute keys and the variable nesting depth.

**Tests.** `test/test_mhd_linear_validation_plots.py::test_the_stride_annotation_survives_the_imas_code_parameters_decode`
is parametrized over both shapes and calls `ods.codeparams2dict()` — the transformation that broke
it. Verified green just now on `6c81505`:

```
python -m pytest -q test/test_mhd_linear_validation_plots.py -k stride
3 passed, 22 deselected
```

**One detail from the fix worth recording**, because it explains why this was easy to miss: omas
raises internally on repeated `<solver>` elements, swallows the error and leaves the string
untouched. So a shot mapped with several modules kept working, while a single-fragment shot decoded
cleanly and lost the annotation — the string-only reader was working by accident on the common case.

Closing as resolved.
