### ISSUE TITLE
[Database] Upgrade h5pyd to 1.x and qualify modern HSDS tabular/query capabilities

### ISSUE THREAD

**Issue by HongSik-Yun-Fusion** [VEST-Tokamak/vaft#1083]
## Background

VAFT currently pins:

```text
h5pyd==0.20.0
```

while the upstream `h5pyd` package has moved to the 1.x series.

VAFT already relies heavily on `h5pyd` for lazy HSDS access through the database layer, including:

- named HSDS sources;
- `vaft.database.open()`;
- `HSDSStore` / lazy ODS access;
- IDS-domain discovery;
- partial dataset selection;
- HSDS publication and replication workflows.

At the same time, several planned database capabilities require HSDS to support more than per-shot IMAS HDF5 payloads.

Two immediate examples are:

1. continuous monitoring data (#1055);
2. materialized scientific summaries/catalogs for future structured database search.

Both are naturally represented as compact tabular HDF5 resources and may benefit from modern HSDS compound-dataset query capabilities.

This issue should therefore treat the h5pyd upgrade not as a dependency-only change, but as a qualification of the modern HSDS client capabilities that VAFT intends to build on.

---

## Goal

Upgrade VAFT from the legacy `h5pyd==0.20.0` client to a supported 1.x release and establish a tested common HSDS tabular-resource layer suitable for:

```text
existing IMAS / ODS access
+
continuous monitoring
+
scientific summary materialization
+
structural data catalogs
+
future database search
```

The intended dependency direction is:

```text
h5pyd 1.x
    ↓
qualified HSDS primitives
    ├── ordinary HDF5 datasets
    ├── compound/tabular datasets
    ├── metadata/attributes
    ├── append/replace
    └── server-side query where supported
    ↓
shared VAFT HSDS table helpers
    ↓
    ├── monitoring
    ├── summary/catalog
    └── database.search()
```

---

## 1. Upgrade the dependency

Replace the current pin:

```toml
h5pyd==0.20.0
```

with an appropriate 1.x constraint after compatibility testing.

Prefer a constrained supported range rather than an unbounded dependency, for example conceptually:

```toml
h5pyd>=1.0,<2
```

or a narrower tested range if required by the deployed HSDS server.

The exact pin should be based on integration testing rather than chosen only from package metadata.

---

## 2. Preserve the current lazy IMAS/ODS path

The upgrade must not regress the existing database contract.

At minimum verify:

```python
vaft.database.open(...)
vaft.database.load(...)
```

and the underlying:

```text
HSDSStore
HSDSODS
discover_hsds_ids()
source resolution
lazy leaf loading
partial dataset selection
```

behave consistently with the current implementation.

Tests should cover:

- occurrence-zero IMAS HDF5 resources;
- IDS-domain discovery without payload materialization;
- lazy leaf access;
- AOS shape handling;
- cached reads;
- partial hyperslab selection;
- closed-store behavior;
- missing IDS behavior;
- source aliases/projections;
- sparse sources.

The upgrade should not force full ODS materialization where lazy access currently works.

---

## 3. Qualify compound/tabular HDF5 datasets

VAFT now has use cases that are fundamentally tabular rather than IMAS-tree-shaped.

Reference structures include scientific summary tables such as:

```text
shot
eq_index
time_s
ip_kA
q_95
beta_normal
li_3
...
```

and continuous monitoring tables such as:

```text
time_ns
signal_id
value
quality
...
```

Verify that h5pyd 1.x and the deployed HSDS server reliably support compound datasets with:

- integer fields;
- floating-point fields;
- fixed or variable string fields where required;
- missing-value conventions;
- slicing;
- field selection;
- append/resize where appropriate;
- attribute metadata.

A minimal representative dataset should be exercised in CI where possible and against the real HSDS deployment in an integration test.

---

## 4. Qualify server-side dataset queries

Modern h5pyd/HSDS exposes query-oriented operations for compound datasets.

VAFT should explicitly test whether these can support predicates such as:

```text
q_95 >= 2.5
AND
q_95 <= 4.0
AND
ip_kA >= 100.0
```

or:

```text
time_ns >= start
AND
time_ns < end
```

Representative use:

```python
result = dataset.query(
    "(q_95 >= 2.5) & (q_95 <= 4.0) & (ip_kA >= 100.0)"
)
```

The exact query syntax should follow the supported h5pyd/HSDS API.

Qualification should cover at least:

- numeric range predicates;
- multiple conjunctive predicates;
- field projection where supported;
- empty matches;
- large result sets;
- ordering guarantees, if any;
- error behavior for unsupported predicates;
- compatibility with compound dtypes used by VAFT.

Do not make future public VAFT search semantics depend directly on raw h5pyd query strings.

---

## 5. Provide a local-filter fallback

Server-side query pushdown is an optimization and transport capability, not the scientific query contract.

If a backend or deployment does not support a required query operation, VAFT should be able to fall back to:

```text
read compact tabular resource
    ↓
construct DataFrame
    ↓
apply equivalent local predicate
```

The result must be semantically identical.

Conceptually:

```python
rows = query_table(...)

# internally:
# 1. try HSDS predicate pushdown
# 2. otherwise read the compact table and filter locally
```

Public APIs should not change depending on whether predicate pushdown was available.

---

## 6. Add shared internal HSDS tabular-resource helpers

Monitoring and future scientific search should not independently reimplement compound-table I/O.

Add a small shared internal abstraction, conceptually:

```python
write_table(...)
read_table(...)
query_table(...)
append_table(...)
```

The exact ownership/module name can be decided during implementation.

The helpers should own generic storage mechanics only:

```text
dtype conversion
dataset creation
resize / append
replace
attributes
query dispatch
fallback filtering
```

They must not own scientific meaning.

For example:

```text
database summary definitions
    belong to SummaryPreset

monitoring signal definitions
    belong to monitoring

query_table()
    only knows how to query a tabular HSDS resource
```

---

## 7. Keep HSDS as a general VAFT data service

This upgrade should support the architectural direction introduced by #1055:

```text
HSDS != IMAS-only storage
```

Instead, VAFT may use HSDS for several logical resource families:

```text
VAFT HSDS
├── scientific / IMAS products
├── monitoring
├── catalog
└── summary
```

The non-IMAS resources do not need to masquerade as IMAS IDS.

Their representation should be purpose-specific HDF5 while still using the common VAFT database access conventions.

---

## 8. Monitoring use case

Issue #1055 proposes continuous monitoring resources indexed by absolute time.

The common HSDS table layer should be capable of supporting structures such as:

```text
time_ns
signal
value
status
```

with queries such as:

```text
start <= time_ns < end
```

This issue does not implement the monitoring representation itself, but should provide and validate the HSDS primitives required by that implementation.

---

## 9. Scientific summary/search use case

VAFT already has canonical summary presets such as:

```text
shot_overview
equilibrium_global
core_profiles
volume_averaged
neoclassical
efit_magnetic_reliability
efit_kinetic_reliability
```

Future structured scientific search should not execute these potentially expensive extractors for every query.

Instead, canonical summary results may be periodically materialized into compact HSDS tables:

```text
canonical ODS / IDS
        ↓
SummaryPreset
        ↓
materialized HSDS summary
        ↓
structured database search
```

Representative equilibrium table:

```text
shot
source
eq_index
time_s
ip_kA
q_95
beta_normal
li_3
...
```

The scientific definition remains owned by `SummaryPreset`; the HSDS table is a replaceable materialization.

This issue should ensure the underlying h5pyd/HSDS capabilities are sufficient for such a design.

---

## 10. Preserve source/provenance metadata

Generic table resources should be able to carry metadata such as:

```text
schema name
schema version
generated_at
VAFT version
DD version
source
producer
row count
covered range
```

For materialized summaries, this may include:

```text
summary preset
preset/schema revision
upstream source
generation revision
```

For monitoring resources:

```text
source database
covered time range
conversion version
```

The table helper should support these attributes without defining their domain-specific contents.

---

## 11. Append, replace, and regeneration semantics

Different resource families need different update behavior.

### Continuous monitoring

Likely requires:

```text
append new time range
replace/repair overlapping interval
```

### Scientific summaries

Likely requires:

```text
regenerate selected shots/source
replace matching rows
full rebuild
```

The shared storage layer should expose sufficient primitives for these operations without forcing one policy onto every consumer.

Do not make an HSDS materialization the scientific source of truth.

For summaries:

```text
SummaryPreset / canonical processing
    = source of truth

HSDS summary
    = replaceable materialized representation
```

---

## 12. Compatibility with existing HSDS tooling

Verify the upgraded client against the operational HSDS workflow where relevant, including:

```text
hsconfigure
hsls
hstouch
hsload / hsget or equivalent supported tools
```

Also verify:

- authentication/configuration handling;
- folder creation/access;
- read/write permissions;
- nested source paths;
- large remote datasets;
- failure behavior when the service is unavailable.

Do not silently change VAFT source or authentication semantics as part of this dependency upgrade.

---

## 13. Performance qualification

Add representative benchmarks or integration measurements for:

### Existing lazy ODS

```text
IDS discovery
single-leaf access
small subtree access
```

### Tabular data

```text
full compact-table read
single-field read
range query with server-side pushdown
equivalent local filtering
append/write
```

The goal is not to impose universal timing thresholds immediately, but to ensure the 1.x upgrade does not introduce major regressions and to quantify the value of server-side filtering.

---

## 14. Public API impact

This issue should not expose raw h5pyd objects as new public VAFT interfaces.

Ordinary users should continue to use APIs such as:

```python
vaft.database.open(...)
vaft.database.load(...)
```

and future higher-level APIs such as:

```python
vaft.database.load_monitoring(...)
vaft.database.search(...)
```

The new tabular-resource helpers are primarily backend infrastructure.

Raw `dataset.query(...)` expressions should remain an implementation detail rather than becoming the public scientific query language.

---

### Phase 1 — h5pyd 1.x compatibility

- upgrade dependency;
- run existing database/lazy-HSDS tests;
- fix compatibility issues;
- validate against the production/test HSDS deployment.

### Phase 2 — compound-table qualification

- create/read/write compound datasets;
- field selection;
- resize/append;
- metadata attributes;
- deterministic dtype conversion.

### Phase 3 — query qualification

- numeric range query;
- compound predicate;
- projected results;
- empty/large result sets;
- error handling.

### Phase 4 — shared table helpers

Add generic internal:

```text
read
write
append
replace
query
```

operations with local fallback.

### Phase 5 — downstream adoption

Allow:

- #1055 monitoring;
- materialized summary/catalog resources;
- future `vaft.database.search()`;

to reuse the common infrastructure.

---

## Non-goals

This issue does **not** implement:

- the monitoring signal model itself;
- monitoring SQL adapters;
- semantic scientific search;
- `vaft.database.search()` itself;
- summary scientific definitions;
- a new IMAS IDS;
- arbitrary SQL syntax over HSDS;
- a public raw h5pyd query API;
- vector/embedding search;
- a general dataframe database;
- replacement of existing named-source semantics.

---

### Upgrade

- [ ] VAFT no longer pins `h5pyd==0.20.0`.
- [ ] A tested h5pyd 1.x version/range is declared.
- [ ] Existing lazy HSDS/ODS database tests pass.
- [ ] Existing source resolution and sparse-source behavior are unchanged.
- [ ] Production/test HSDS compatibility is verified.

### Existing IMAS access

- [ ] IDS discovery still works without loading waveform/scientific payloads.
- [ ] Lazy leaf access remains functional.
- [ ] Partial dataset selection remains functional.
- [ ] AOS/shape handling remains functional.
- [ ] No new full-ODS materialization is introduced.

### Tabular resources

- [ ] Compound datasets can be created and read through h5pyd 1.x.
- [ ] Numeric, string, and mixed compound fields required by VAFT are qualified.
- [ ] Attributes/provenance metadata can be stored and recovered.
- [ ] Append/resize semantics are qualified.
- [ ] Replace/regeneration operations can be implemented safely.

### Query capability

- [ ] Numeric range queries on compound datasets are verified against HSDS.
- [ ] Multiple predicates can be combined.
- [ ] Empty result sets are handled normally.
- [ ] Query failures have explicit error semantics.
- [ ] Equivalent local filtering produces the same result.
- [ ] Public VAFT APIs do not expose backend-specific query strings.

### Shared infrastructure

- [ ] Monitoring and future summary/search code can reuse one internal HSDS tabular-resource implementation.
- [ ] Generic storage helpers contain no monitoring- or physics-specific semantics.
- [ ] Server-side query pushdown is used where supported.
- [ ] A local filtering fallback exists where pushdown is unavailable.
- [ ] The same tabular representation can be mirrored locally if needed.

### Documentation

- [ ] Document the qualified h5pyd/HSDS feature set used by VAFT.
- [ ] Document compatibility assumptions with the deployed HSDS version.
- [ ] Document the distinction between IMAS resources and non-IMAS VAFT HSDS resources.
- [ ] Document the role of HSDS table materializations as derived/replaceable resources.

---

## Related

- #1055 — continuous monitoring data layer
- #127 — canonical preset-based database summaries
- #513 — source-aware scientific record discovery
- future structured scientific search issue

---

## Design principle

```text
HSDS is not only a remote IMAS file store.

For VAFT it should provide a common HDF5-backed data service for:

    scientific payloads
    + continuous monitoring
    + structural catalogs
    + materialized scientific summaries

while domain semantics remain owned by their respective VAFT layers.
```

The purpose of the h5pyd 1.x migration is therefore not merely to modernize a dependency, but to establish and qualify the HSDS primitives required by the next generation of VAFT database discovery and monitoring workflows.
